---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: install apt
    yum:
      name: apt
      state: present


  - name: update apt
    yum:
      name: apt
      state: latest

